mini_batch_size: 1
batch_num_per_epoch: 100_000
replay_buffer_size: 1
training_steps: 500_000_000
skip_k_frame: 4
phi_channel: 4
device: 'cpu'
screen_size: 84
gamma: 0.99
no_op: 10
save_path: './exps/'
log_path: '../exps/async_dqn/'
learning_rate: 0.00001
step_c: 10_000
epsilon_max: 1.
epsilon_min: 0.1
exploration_steps: 5_000_000
epsilon_for_test: 0.05
agent_test_episodes: 20
agent_saving_period: 80000
worker_num: 1
