mini_batch_size: 32
batch_num_per_epoch: 100_000
replay_buffer_size: 32
training_steps: 50_000_000
skip_k_frame: 4
phi_channel: 4
device: 'cuda: 0'
input_frame_width: 84
input_frame_height: 84
replay_start_size: 32
gamma: 0.99
no_op: 30
save_path: './exps/'
log_path: '../exps/async_dqn/'
learning_rate: 0.00001
step_c: 1_000
epsilon_max: 1.
epsilon_min: 0.1
exploration_steps: 100_000
epsilon_for_test: 0.05
agent_test_episodes: 20
agent_saving_period: 80000
