mini_batch_size: 32
batch_num_per_epoch: 250_000
replay_buffer_size: 1_000_000
training_steps: 50_000_000
skip_k_frame: 4
phi_channel: 4
model_update_freq: 4
device: 'cuda: 0'
screen_size: 84
replay_start_size: 50_000
gamma: 0.99
no_op_max: 30
exp_path: '../exps/dqn/'
learning_rate: !!float 2.5e-4
step_c: 10_000
epsilon_max: 1.
epsilon_min: 0.1
exploration_steps: 1_000_000
epsilon_for_test: 0.05
agent_test_episodes: 20
held_out_states_num: 1000
seed: 42