name: Generate HTML Document

on:
  push:
    branches:
      - dev  # 触发工作流的分支
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 指定 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jinja2  # 假设依赖文件在docs文件夹中

    - name: Run Python script
      run: python docs/generate_html.py  # 指定脚本在docs文件夹下

    - name: Upload HTML document
      uses: actions/upload-artifact@v2
      with:
        name: html-documents
        path: docs/htmls/*  # 上传docs/htmls文件夹下所有文件
